[build]
  # Diretório onde estão as funções serverless
  functions = "src/functions"

  # Diretório onde estão os arquivos a serem publicados (raiz)
  publish = "."

# Configurações de redirecionamento para as funções serverless
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
