[build]
  functions = "src/functions"   # Caminho para a pasta onde estão as funções serverless
  publish = "."                 # Diretório de publicação (a raiz do projeto)

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
